providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = ["npm --prefix backend ci --omit=dev --no-audit --no-fund", "npm --prefix frontend ci --include=dev --no-audit --no-fund"]
